Deployment - Adding merge check against develop

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -101,7 +101,7 @@ jobs:
             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/smart_fridge_laravel:latest
             echo "Starting containers..."
             sudo docker compose up -d
-
+            
   deploy-to-production:
     needs: build-and-push
     if: github.ref == 'refs/heads/main'
@@ -110,6 +110,14 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - name: Validate main is merged from develop
+        run: |
+          git fetch origin develop
+          git merge-base --is-ancestor origin/develop HEAD || {
+            echo "ERROR: main is not up to date with develop"
+            exit 1
+          }
 
       - name: Deploy to PRODUCTION EC2
         uses: appleboy/ssh-action@v0.1.10
